[package]
name = "perbase"
version = "0.1.0"
authors = ["Seth Stadick <sstadick@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = "0.32.0"
log = "0.4.11"
env_logger = "0.7.1"
anyhow = "1.0.32"
argh = "0.1.3"
